#!/bin/sh
# Useage: ./load3531a [ -r|-i|-a ] [ ad ]
#         -r : rmmod all modules
#         -i : insmod all modules
#    default : rmmod all moules and then insmod them
#

####################Variables Definition##########################
AD_TYPE=2823        # ad type

mem_total=1024;		# 512M, total mem
mem_start=0x40000000;	# phy mem start

os_mem_size=128;		# 64M, os mem
mmz_start=0x48000000;	# mmz start addr
mmz_size=888M;		# 128M, mmz size

##################################################################

report_error()
{
	echo "******* Error: There's something wrong, please check! *****"
	exit 1
}

insert_audio()
{
	insmod hi3531a_aio.ko
	insmod hi3531a_ai.ko
	insmod hi3531a_ao.ko
	insmod hi3531a_aenc.ko
	insmod hi3531a_adec.ko
#	insmod extdrv/tlv_320aic31.ko 
	echo "insert audio"
}

remove_audio()
{
#	rmmod tlv_320aic31.ko
	rmmod hi3531a_adec
	rmmod hi3531a_aenc
	rmmod hi3531a_ao
	rmmod hi3531a_ai
	rmmod hi3531a_aio
	echo "remove audio"
}

insert_ad()
{
	case $AD_TYPE in
		6124)
			insmod extdrv/nvp6124.ko
			;;
		2823)
			insmod extdrv/tp2823.ko
			;;
		*)
			echo "xxxx Invalid ad type $AD_TYPE xxxx"
			report_error
			;;
	esac
}

remove_ad()
{
	case $AD_TYPE in
		6124)
			rmmod nvp6124
			;;
		2823)
			rmmod tp2823
			;;			
		*)
			echo "xxxx Invalid ad type $AD_TYPE xxxx"
			report_error
			;;
	esac
}

# If you want to use PCIe cascade, please compile PCIe related uboot, kernel, rootfs in directory: osdrv/.
# Also, please compile PCIe related ko files in directory: osdrv/pub/. Then create a directory named pcie in current directory,
# and put theses ko files in the directory.  
# For more details, please read the files in directory: osdrv/ and osdrv/drv/pcie_mcc/.

insert_pci()
{
    insmod pcie/hi35xx_dev_slv.ko
    insmod pcie/pcit_dma_slv.ko
    insmod pcie/mcc_drv_slv.ko shm_phys_addr=0x7F800000 shm_size=0x100000
    insmod pcie/mcc_usrdev_slv.ko

    insmod hi3531a_pciv_fmw.ko
    insmod hi3531a_pciv.ko
}

remove_pci()
{
	rmmod hi3531a_pciv.ko
    rmmod hi3531a_pciv_fmw.ko
	
    rmmod mcc_usrdev_slv.ko
    rmmod mcc_drv_slv.ko
    rmmod pcit_dma_slv.ko
    rmmod hi35xx_dev_slv.ko 
}

insert_ko()
{
	# low power control
	# source ./lowpower.sh > /dev/null

	# pinmux configuration
	source ./padctrl_hi3531a.sh > /dev/null
	source ./pinmux_vicap_i2c_i2s.sh > /dev/null
#	source ./pinmux_bt1120.sh > /dev/null
#	source ./pinmux_master.sh > /dev/null
#	source ./pinmux_slave.sh > /dev/null

	# crg configuration
	source ./crgctrl_hi3531a.sh > /dev/null

	# system configuration
	source ./sysctl_hi3531a.sh > /dev/null

	# driver load
	insmod mmz.ko mmz=anonymous,0,$mmz_start,$mmz_size:window,0,0x7F900000,7M anony=1 || report_error
	insmod hiuser.ko
	insmod hi_media.ko
	insmod hi3531a_base.ko
	insmod hi3531a_sys.ko
	insmod hi3531a_vdec.ko
	insmod hi3531a_vfmw.ko 
	insmod hi3531a_jpegd.ko
	insmod hi3531a_tde.ko
	insmod hi3531a_region.ko
	insmod hi3531a_vgs.ko
	insmod hi3531a_viu.ko detect_err_frame=10;	
	
	insmod hi3531a_vpss.ko
	insmod hi3531a_vou.ko
	insmod hifb.ko video="hifb:vram0_size:32400,vram1_size:8100,vram2_size:2160,vram3_size:128,vram4_size:128" softcursor="off"
	insmod hi3531a_hdmi.ko

	insmod hi3531a_rc.ko
	insmod hi3531a_venc.ko
	insmod hi3531a_chnl.ko
	insmod hi3531a_h264e.ko
	insmod hi3531a_jpege.ko
	insmod hi3531a_vda.ko
	insmod hi3531a_ive.ko

	#insmod extdrv/sil9024.ko norm=5   #720P@60fps
	#insmod extdrv/sil9024.ko norm=9   #1080P@60fps
    	#insmod extdrv/sil9024.ko norm=12   #1080P@30fps

#	echo "==== Your input AD type is $AD_TYPE ===="
	insert_ad

	insert_audio
	insert_pci
}

remove_ko()
{
	remove_pci
	remove_audio
	remove_ad

	rmmod sil9024 &> /dev/null

	rmmod hi3531a_ive
	rmmod hi3531a_vda

	rmmod hi3531a_rc
	rmmod hi3531a_jpege
	rmmod hi3531a_h264e
	rmmod hi3531a_chnl
	rmmod hi3531a_venc

	rmmod hi3531a_hdmi
	rmmod hifb
	rmmod hi3531a_vou
	rmmod hi3531a_vpss
	rmmod hi3531a_viu

	rmmod hi3531a_vgs
	rmmod hi3531a_region
	rmmod hi3531a_tde

	rmmod hi3531a_jpegd
	rmmod hi3531a_vfmw
	rmmod hi3531a_vdec
	rmmod hi3531a_sys
	rmmod hi3531a_base
	rmmod hi_media
	rmmod hiuser
	rmmod mmz
}

load_usage()
{
	echo "Usage:  ./load3531a [-option] [ad_name]"
	echo "options:"
	echo "    -i                       insert modules"
	echo "    -r                       remove modules"
	echo "    -a                       remove modules first, then insert modules"
	echo "    -ad ad_name              config AD type [default: nvp6124]"
	echo "    -osmem os_mem_size       config os mem size [unit: M, default: 64]"
	echo "    -h                       help information"
	echo -e "Available ad: nvp6124, tp2823"
	echo -e "notes: osmem option can't be used when mmz zone partition is enable\n\n"
	echo -e "for example: ./load3531a -a -ad 6124 -osmem 64\n"
}

calc_mmz_info()
{
	mmz_start=`echo "$mem_start $os_mem_size" | 
	awk 'BEGIN { temp = 0; }
	{
		temp = $1/1024/1024 + $2;
	} 
	END { printf("0x%x00000\n", temp); }'`

	mmz_size=`echo "$mem_total $os_mem_size" | 
	awk 'BEGIN { temp = 0; }
	{
		temp = $1 - $2;
	} 
	END { printf("%dM\n", temp); }'`
	echo "mmz_start: $mmz_start, mmz_size: $mmz_size"
}


######################parse arg###################################
b_arg_os_mem=0
b_arg_ad=0
b_arg_insmod=0
b_arg_remove=0

for arg in $@
do
	if [ $b_arg_os_mem -eq 1 ] ; then
		b_arg_os_mem=0;
		os_mem_size=$arg;

		if [ -z $os_mem_size ]; then
			echo "[error] os_mem_size is null"
			exit;
		fi

		if [ $os_mem_size -ge $mem_total ] ; then
			echo "[err] os_mem[$os_mem_size], over total_mem[$mem_total]"
			exit;
		fi

		calc_mmz_info;
	fi

	if [ $b_arg_ad -eq 1 ] ; then
		b_arg_ad=0
		AD_TYPE=$arg;
	fi

	case $arg in
		"-i")
			b_arg_insmod=1;
			;;

		"-r")
			b_arg_remove=1;
			;;
		"-a")			
			b_arg_insmod=1;
			b_arg_remove=1;
			;;

		"-h")
			load_usage;
			;;

		"-ad")
			b_arg_ad=1;
			;;

		"-osmem")
			b_arg_os_mem=1;
			;;
	esac
done
#######################parse arg end########################

#######################Action###############################
if [ $b_arg_remove -eq 1 ]; then
	remove_ko;
fi
if [ $b_arg_insmod -eq 1 ]; then
	insert_ko;
fi

